services:
  - type: web
    name: flask-chat-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://chatuser:AkhilChat2025%21@cluster2.a5gequu.mongodb.net/chatdb?retryWrites=true&w=majority
